project_id = "sbhzectozelcjwnoaaaw"

[functions.elevenlabs-tts]
verify_jwt = false

[functions.stability-image]
verify_jwt = false

[functions.replicate-image]
verify_jwt = false

[functions.openai-image]
verify_jwt = false

[functions.chat-grok]
verify_jwt = false

[functions.chat-groq]
verify_jwt = false

[functions.chat-openai]
verify_jwt = false

[functions.chat-claude]
verify_jwt = false

[functions.chat-mistral]
verify_jwt = false
